### ISSUE TITLE
Puppet Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class mcollective_choria

### ISSUE THREAD

**Issue by timdeluxe** [choria-plugins/mcollective_choria#17]
We configure mcollective_choria class like this:
```
    class {
      'mcollective_choria':
        config => {
           ...
```
From time to time we get this error:
`Puppet Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class mcollective_choria`
Especially when deploy new puppet code with r10k. Nearly everytime when we do changes on the Puppetfile, but also often, when Puppetfile was not touched and only manifests were changed or added.
Next puppet run on problematic servers runs fine and it is only this class, which can't be found, when it happens.

Is that known? Has anyone experienced a similar / the same issue and found a solution?

Our current only idea for mitigation is to activate/implement environment_cache...

**Comment by ripienaar** [comment]
I have not seen this, but the puppet server might log some extra stuff? For example it used to log syntax errors and then report cant find the class in this manner - there might be something like that?

Past that, no never seen this or heard of someone who saw this.

**Comment by timdeluxe** [comment]
@ripienaar Well there is log around that, but not really helpful.
After the error there is a pretty long stracktrace beginning with
`/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource.rb:315:in initialize'`
and ending with
`/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:737:in eval_Program'`
Sometimes we have also
```
Puppet Not Found: Could not find file_metadata modules/mcollective_choria/mcollective/agent/scout.ddl
Puppet Not Found: Could not find file_metadata modules/mcollective_choria/mcollective/agent/scout.json
Puppet Not Found: Could not find file_metadata modules/mcollective_choria/mcollective/agent/rpcutil.ddl
Puppet Not Found: Could not find file_metadata modules/mcollective_choria/mcollective/agent/rpcutil.json
Puppet Not Found: Could not find file_metadata modules/mcollective_choria/mcollective/agent/choria_util.ddl
Puppet Not Found: Could not find file_metadata modules/mcollective_choria/mcollective/agent/choria_util.json
```
This all sounds like a race condition on r10k deployments, but i am pretty puzzled why that only affects this module...

**Comment by ripienaar** [comment]
Yeah does sound like some kind of race. Do you r10k deploy directly to the puppet server or first into a temp directory the symlink or move? Doing an atomic move of an entirely deployed code dir would probably help

but yeah I can’t see anything this module does that might cause that

**Comment by timdeluxe** [comment]
We are doing pretty standard deployments via
`r10k deploy environment --puppetfile <environment_name>`
Atomic move might help, but i think if you don't know anything else which might help us, we rather go ahead with environment_cache, which can give us also some performance boost.
Will keep the issue open to report, if that works around the problem.

Thanks for your feedback so far.

**Comment by timdeluxe** [comment]
environment_cache helped. Since we activated and use it, the issue did not occur again.
